### ISSUE TITLE
mbedtls missing / build failing

### ISSUE THREAD

**Issue by Informatic** [cpp3ds/cpp3ds#3]
Hi,
seems like mbedtls is missing from current master branch.

Also i've stumbled upon multiple problems when trying to setup cpp3ds in my environment, if you want, i will create separate issues for these:
- [ ] Latest release version makerom fails on current devkitARM (`malloc(): memory corruption`) - fixed by rebuilding latest makerom manually
- [ ] Latest release version fails with `/home/travis/build/cpp3ds/cpp3ds/src/emu3ds/Emulator/Emulator.cpp:123: undefined reference to "sf::Image::saveToFile(std::string const&) const"`
- [ ] On second-to-last commit template project (after fixing `game.console` invocation) fails to build because of missing `-D_GLIBCXX_USE_CXX11_ABI=0` flag, `citro3d` lib for 3ds build, and `Qt5Gui Qt5Widgets` libs for emu build (after some more tweaks i might not remember right now - built binary does not boot on 3ds, and emu build segfaults anyway :3)

So, yeah. I sadly didn't succeed to build anything, but it feels like a pretty useful piece of toolkit... :)

(setup: latest devkitarm, ctrulib master, citro3d master, ubuntu 15.10, system gcc 5.2.1, system sfml 2.3.2)

**Comment by Cruel** [comment]
Sorry for the delayed response, I've been busy.

I have been unfortunately pushing a lot of stuff directly to master, been reckless about breaking it, and I still have a lot of stuff yet to push locally. Within the next couple weeks, it's my goal to clean this up and get it building again.

I obviously have it building locally and use it in a couple projects of mine (DrawAttack and BrewMan), so won't require much to get it working, it's more a matter of cleaning up master and start branching properly. lol

**Comment by Informatic** [comment]
Thank you very much and keep up the good work :3

**Comment by krruzic** [comment]
so, I just /almost/ built this. Had trouble with mbedtls when I was compiling it. There's one function there that looks for the ipv6 definition struct which libctru doesn't support (I'm assuming the 3ds doesn't support ipv6 at all?). I just returned some mbed error and it compiled fine. I can upload a gist with the patched file and a fixed up cmake for mbedtls if you'd like @Informatic.

Only problem I have is coming from citro3d. 
I'm getting this:
`/home/kristopher/cpp3ds/src/cpp3ds/Graphics/Shader.cpp:238:114: error: invalid conversion from 'const C3D_Mtx*' to 'C3D_Mtx*' [-fpermissive]`

Citro might have changed the functions since your code was written, so I'll give it a look. Great library by the way.

I should note, I didn't use travis, I just ran cmake and the build scripts.

**Comment by Cruel** [comment]
Okay, I have removed mbedtls dependency, now emulator just need openssl which most people already have.

Also I just fixed the issue with `const C3D_Mtx`, you just need to update to latest citro3d.

And the makerom issue would be a problem with [3ds-tools](https://github.com/cpp3ds/3ds-tools). I'm updating that repo now with latest tools.

**Comment by Cruel** [comment]
And thanks for the _GLIBCXX_USE_CXX11_ABI hint. Travis-ci has outdated toolchains, but I should be able to tweak it to use newer ABI.

**Comment by Cruel** [comment]
Pre-compiled releases use newer CXX_ABI now. And all listed issues are solved.
